In [ ]:
import pandas as pd
a = [1,21,2,2,2,2,2,4,5,56,7,8,7,9]
series_a = pd.Series(a)
print(type(series_a))
print('Asscending order: ',series_a.sort_values)

<class 'pandas.core.series.Series'>
Asscending order:  <bound method Series.sort_values of 0      1
1     21
2      2
3      2
4      2
5      2
6      2
7      4
8      5
9     56
10     7
11     8
12     7
13     9
dtype: int64>


In [ ]:
import numpy as np
import pandas as pd

data = {
    "Energy Source":["Solar", "Wind", "Hydropower", "Geothermal", "Biomass","Nuclear"],
    "Energy Consumption(MWh)": [ 1200,np.nan, 2900, np.nan, 2500, 3200],
    "Cost (Million $)" : [200, 400, np.nan, 150, 250, np.nan]

}
df = pd.DataFrame(data)
df

,Energy Source,Energy Consumption(MWh),Cost (Million $)
0,Solar,1200.0,200.0
1,Wind,NaN,400.0
2,Hydropower,2900.0,NaN
3,Geothermal,NaN,150.0
4,Biomass,2500.0,250.0
5,Nuclear,3200.0,NaN


In [ ]:
for i in range(6):
  print(i)

0
1
2
3
4
5


In [ ]:
for i in range(3, 9):
  print(i)

3
4
5
6
7
8


In [ ]:
for i in range(4, 10, 1):
  print(i)

4
5
6
7
8
9


In [ ]:
list_1 = []

for i in range(10):
  list_1.append(i)
  list_1.append(i+1)
  list_1.append(i+2)

print(list_1)
print(list_1[0])
list_1[4]

[0, 1, 2, 1, 2, 3, 2, 3, 4, 3, 4, 5, 4, 5, 6, 5, 6, 7, 6, 7, 8, 7, 8, 9, 8, 9, 10, 9, 10, 11]
0


2

In [ ]:
i = 0
while i<8:
  print(i)
  i=i+1

0
1
2
3
4
5
6
7


In [ ]:
user_input = ' '
while user_input.lower() != 'quit':
      user_input = input("Enter something(type 'quit' to stop): ")
      print("You entered:", user_input )

You entered: Hello
You entered: good morning


In [1]:

def greet():
    print('Day 2 8/7/26')
greet()
print('Outside function')

Day 2 8/7/26
Outside function


In [12]:
def something(i, j):
  mul = i*i
  div = mul / j
  list_1 = []
  for i in range(mul):
    list_1.append(i)
    print(list_1)

    list_1 = []

    while j<4:
      print(j)
      j = j+1

    return mul, div

  something(2,2)

In [16]:
import numpy as np
d_0 = np.array(42) #0d
d_1 = np.array([42,421,423,424]) #1d
d_2 = np.array([  #2d
    [1,2,3],
    ('x', 'y', 'z',),
    ('x', 'y', 'z',),
    ('x', 'y', 'z',),
    ('x', 'y', 'z',)
])

d_3 = np.array([
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ],

               [
                   [11,22,33],
                   [44,55,66],
                   [77,88,99]
               ]
]
)

In [9]:
import numpy as np

d_0 = np.array(42)

d_1 = np.array([55, 420, 380, 534])

d_2 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

d_3 = np.array([
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ],

    [
        [10,12,14],
        [15,18,30],
        [33,35,36]
    ]
])

print("Size of d3 is: ", d_3.size)
print("Dimensions of d3 are: ", d_3.ndim)

flattened_array = d_2.flatten()
print("Dimensions of flattened array is ", flattened_array.ndim)
print("Size of flattened array is: ", flattened_array.size)

Size of d3 is:  18
Dimensions of d3 are:  3
Dimensions of flattened array is  1
Size of flattened array is:  9


In [8]:
import numpy as np

d_0 = np.array(42)

d_1 = np.array([42, 421, 423, 424])

d_2 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

d_3 = np.array([
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ],
    [
        [10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]
    ]
])


print(np.ndim(d_0), d_0)
print(np.ndim(d_1), d_1)
print(np.ndim(d_2), d_2)
print(np.ndim(d_3), d_3)

0 42
1 [ 42 421 423 424]
2 [[1 2 3]
 [4 5 6]
 [7 8 9]]
3 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


In [7]:
import numpy as np

# 1-D Array
a = np.array([10, 20, 30, 40, 50])
print("1-D Array:")
print(a)

# 2-D Array
b = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print("\n2-D Array:")
print(b)

# 3-D Array
d = np.array([
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ],
    [
        [10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]
    ]
])
print("\n3-D Array:")
print(d)

# Accessing elements
print("\nElement at d[1,2,1] =", d[1,2,1])
print("Element at d[0,1,2] =", d[0,1,2])

# Array properties
print("\nShape:", d.shape)
print("Size:", d.size)
print("Dimensions:", d.ndim)

# Reshape
reshaped = d.reshape(3, 6)
print("\nReshaped Array:")
print(reshaped)

# Flatten
flattened = d.flatten()
print("\nFlattened Array:")
print(flattened)


1-D Array:
[10 20 30 40 50]

2-D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

3-D Array:
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]

Element at d[1,2,1] = 17
Element at d[0,1,2] = 6

Shape: (2, 3, 3)
Size: 18
Dimensions: 3

Reshaped Array:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]

Flattened Array:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


In [6]:
import numpy as np

arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])
print("Original Array:")
print(arr)

print("\nElement at [0][1]:", arr[0][1])
print("Element at[2][2]:", arr[2][2])

print("\nAddition:", arr +5)
print("\nSubstraction:", arr -5)
print("\nMultiplication:", arr *2)
print("\nDivision:", arr / 2)

#Numpy Methods
print("\n1. shape:", arr.shape)
print("2. Size:" , arr.size)
print("3. Dimensions:", arr.dimensions)
print("4. Data Type:", arr.dtype)
print("5. Sum:", np.sum(arr))
print("6. Mean:", np.mean(arr))
print("7. Maximum:", np.max(arr))
print("8. Minimum:", np.min(arr))
print("9. Standard Deviation:", np.std(arr))
print("10. Transpose::\n", arr.T)
print("11. Flattern:", arr.flatten())
print("12. Reshape:", arr.reshape(1,9))
print("13. Square Root:\n", np.sqrt(arr))
print("14. Sort:\n", np.sort(arr))
print("15. Unique Value:", np.unique(arr))


Original Array:
[[10 20 30]
 [40 50 60]
 [70 80 90]]

Element at [0][1]: 20
Element at[2][2]: 90

Addition: [[15 25 35]
 [45 55 65]
 [75 85 95]]

Substraction: [[ 5 15 25]
 [35 45 55]
 [65 75 85]]

Multiplication: [[ 20  40  60]
 [ 80 100 120]
 [140 160 180]]

Division: [[ 5. 10. 15.]
 [20. 25. 30.]
 [35. 40. 45.]]

1. shape: (3, 3)
2. Size: 9


AttributeError: 'numpy.ndarray' object has no attribute 'dimensions'